site_name: Redshift Documentation
nav:
  - Data Warehouse User Guide: 'Introduction to Data Warehouse User Guide.md'
  - Foundation Level Queries:
      - Members: 'ReactorCX Data Warehouse User Guide/Foundation Level Queries/Members.md'
      - Activities: 'ReactorCX Data Warehouse User Guide/Foundation Level Queries/Activities.md'
      - Programs: 'ReactorCX Data Warehouse User Guide/Foundation Level Queries/Programs.md'

theme:
  name: material
  logo: 'Images/RCX_Logo.png'
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


# To add Permannat link for headers
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

extra_css:
  - 'css/extra.css'
  - 'custom/custom.css'
  - 'custom/footer.css'

extra_javascript:
  - 'custom/footer.js'